// THE FILE SHELLAPIWORKBENCHVERSIONINFO.TS IS AUTOMATICALLY GENERATED DURING BUILD PROCESS
// MANUAL CHANGES TO THIS FILE WILL BE OVERWRITTEN !!!

export const SHELL_API_WORKBENCH_VERSION_INFO = {
    VERSION : 'Will-Be-Replaced-During-Build',
    BUILD_TS: 'Will-Be-Replaced-During-Build'
};

